"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const register_1 = require("../controller/register");
const login_1 = require("../controller/login");
const retrieve_1 = require("../controller/retrieve");
const edit_user_1 = require("../controller/edit-user");
const nomenclature_1 = require("../controller/nomenclature");
const disciplines_1 = require("../controller/disciplines");
const logs_1 = require("../controller/logs");
const massages_1 = require("../controller/massages");
const text_messages_1 = require("../controller/text-messages");
exports.router = (0, express_1.Router)();
exports.router.post('/create_account', register_1.registerController.create);
exports.router.post('/check_number', register_1.registerController.checkLastNumber);
exports.router.post('/login', login_1.loginController.loginUser);
exports.router.post('/login_email', login_1.loginController.loginWithEmail);
exports.router.post('/login_teacher', login_1.loginController.loginTeacher);
exports.router.post('/retrieve_student', retrieve_1.retrieveController.retrieveStudent);
exports.router.post('/get_student', retrieve_1.retrieveController.getStudent);
exports.router.post('/get_edit_users', edit_user_1.editUserController.retrieveProfile);
exports.router.post('/update_user', edit_user_1.editUserController.updateProfile);
exports.router.post('/update_health_care', edit_user_1.editUserController.updateHealthCare);
exports.router.post('/remove_health_care', edit_user_1.editUserController.removeHealthCare);
exports.router.post('/update_sport', edit_user_1.editUserController.updateSport);
exports.router.post('/remove_sport', edit_user_1.editUserController.removeSport);
exports.router.post('/update_scholarship', edit_user_1.editUserController.updateScholarship);
exports.router.post('/remove_scholarship', edit_user_1.editUserController.removeScholarship);
exports.router.post('/update_dorm', edit_user_1.editUserController.updateDorm);
exports.router.post('/remove_dorm', edit_user_1.editUserController.removeDorm);
exports.router.post('/update_grade', edit_user_1.editUserController.updateGrade);
exports.router.post('/remove_grade', edit_user_1.editUserController.removeGrade);
exports.router.post('/edit_grade', edit_user_1.editUserController.editUser);
exports.router.post('/nom_disc', nomenclature_1.nomController.loadDisc);
exports.router.post('/get_edit_teacher', edit_user_1.editUserController.retrieveTeacher);
exports.router.post('/retrieve_edit_teacher', edit_user_1.editUserController.getTeacher);
exports.router.post('/update_edit_teacher', edit_user_1.editUserController.updateTeacher);
exports.router.post('/retrieve_teacher_list', edit_user_1.editUserController.listTeacher);
exports.router.post('/retrieve_teacher_from_id', retrieve_1.retrieveController.getTeacher);
exports.router.post('/add_discipline', disciplines_1.editDisciplinesController.create);
exports.router.post('/retrieve_all_discipline', disciplines_1.editDisciplinesController.retrieveAll);
exports.router.post('/retrieve_discipline_by_id', disciplines_1.editDisciplinesController.retrieveById);
exports.router.post('/updated_discipline', disciplines_1.editDisciplinesController.updateDisciplines);
exports.router.post('/delete_discipline', disciplines_1.editDisciplinesController.deleteDisciplines);
exports.router.post('/filter_discipline', disciplines_1.editDisciplinesController.filterDisciplines);
exports.router.post('/load_logs', logs_1.retrieveLogs.retrieveLogs);
exports.router.post('/load_messages', massages_1.massageController.retrieveMassages);
exports.router.post('/send_email', massages_1.massageController.sendEmail);
exports.router.post('/send_msg', text_messages_1.textMassages.sendMassage);
exports.router.post('/retrieve_msg', text_messages_1.textMassages.retrieveAllMsg);
